# Generated by Django 5.2.10 on 2026-01-09 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='Student_id',
            new_name='student_id',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='student_photo',
            new_name='student_image',
        ),
    ]
